name: jb_course
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - python=3.10

  # For Python interactive plots
  - bokeh

  # For QuantEcon Book theme
  - pip
  - pip:
    - git+https://github.com/QuantEcon/quantecon-book-theme.git


