name: jb_myst
channels:
  - conda-forge
dependencies:
  - nodejs
  - mystmd
  - jupyter_server
  - ipykernel

  # For Python interactive plots example
  - bokeh
  - numpy

  - ortools-python

  - pip
  - pip:
    - gilp


