name: jb_course
channels:
  - conda-forge
dependencies:
  - jupyter-book

  # Diagrams with Mermaid.js
  - sphinxcontrib-mermaid

  - python=3.10

  # For Python interactive plots example
  - bokeh
  - numpy

  # https://github.com/pydata/pydata-sphinx-theme/issues/1844
  - pydata-sphinx-theme==0.15.2


  - pip
  - pip:
    - sphinx-proof
    - git+https://github.com/QuantEcon/quantecon-book-theme.git


