# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Course template
author: Tunç Başar Köse
logo: logo.png
only_build_toc_files: true

# Code execution settings
execute:
  execute_notebooks: force  # See https://jupyterbook.org/content/execute.html

# File parsing settings
parse:
  myst_enable_extensions:
    - amsmath       # For LaTeX math
    - colon_fence   # Allow use of ::: for admonitions, instead of just ```
    - substitution  # Define and use of markdown "variables"
    - linkify       # Auto-detect HTML-like links and convert them to hyperlinks.
    - dollarmath    # Allow $$ and $ syntax for math blocks

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/gamma-opt/jb_course_template  # Online location of your book
  path_to_book: "course"                                  # Optional path to your book, relative to the repository root
  branch: main                                          # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    html_theme: quantecon_book_theme